"use client";

import type { Mail } from '../../../../mocks/mails';
import { Icon } from '@iconify/react';
import styles from './clickedmail.module.css';

interface ClickedMailProps {
  mail: Mail;
  onClose: () => void;
}

const tagStyles: Record<string, string> = {
  Inbox: styles.tagInbox,
  Delivered: styles.tagDelivered,
  Pending: styles.tagPending,
};

const tagLabel: Record<string, string> = {
  Inbox: 'Processed',
  Delivered: 'Delivered',
  Pending: 'Pending',
};

export default function ClickedMail({ mail, onClose }: ClickedMailProps) {
  return (
    <div
      className={styles.overlay}
      onClick={onClose}
    >
      <div
        className={styles.modal}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className={styles.header}>
          <div className={styles.titleGroup}>
            <div className={styles.mailIconBox}>
              <Icon icon="ri:mail-line" className={styles.iconMail} />
            </div>
            <div>
              <h2 className={styles.subject}>{mail.subject}</h2>
              <p className={styles.metaInfo}>ML-00{mail.id} &bull; Today, {mail.time}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className={styles.closeButton}
          >
            <Icon icon="ri:close-line" className={styles.iconClose} />
          </button>
        </div>

        {/* Document Preview */}
        <div className={styles.documentPreviewBox}>
          <img
            src="https://readdy.ai/api/search-image?query=official%20government%20tax%20document%20letter%20with%20formal%20text%20paragraphs%2C%20white%20paper%2C%20black%20ink%2C%20clean%20document%20layout%2C%20IRS%20notice%20form%2C%20professional%20legal%20document&width=540&height=180&seq=mailpreview1&orientation=landscape"
            alt="Document preview"
            className={styles.documentPreviewImg}
          />
          <div className={styles.documentOverlay}></div>
        </div>

        {/* Recipient & Sender */}
        <div className={styles.detailsGrid}>
          <div className={styles.detailCard}>
            <p className={`${styles.detailLabel} ${styles.labelPrimary}`}>Recipient Company</p>
            <div className={styles.companyGroup}>
              <div className={`${styles.companyAvatar} ${mail.senderColor}`}>
                {mail.company.charAt(0)}
              </div>
              <div>
                <p className={styles.companyName}>{mail.company}</p>
                <p className={styles.companyEmail}>info@{mail.company.toLowerCase().replace(/\s+/g, '')}.com</p>
              </div>
            </div>
          </div>

          <div className={styles.detailCard}>
            <p className={`${styles.detailLabel} ${styles.labelSecondary}`}>Sender</p>
            <p className={styles.senderName}>{mail.sender}</p>
            <span className={`${styles.tagBase} ${tagStyles[mail.tag]}`}>
              {tagLabel[mail.tag]}
            </span>
          </div>
        </div>

        {/* AI Summary */}
        <div className={styles.aiSummaryBox}>
          <div className={styles.aiHeader}>
            <div className={styles.aiIconWrapper}>
              <Icon icon="ri:sparkling-2-fill" className={styles.iconSparkling} />
            </div>
            <span className={styles.aiTitle}>AI-Generated Summary</span>
          </div>
          <p className={styles.aiPreviewText}>{mail.preview}</p>
          <div className={styles.aiFooter}>
            <div className={styles.aiShieldWrapper}>
              <Icon icon="ri:shield-check-line" className={styles.iconShield} />
            </div>
            <span className={styles.aiFooterText}>Generated by VScan AI</span>
          </div>
        </div>

        {/* Actions */}
        <div className={styles.actionsGroup}>
          <button className={styles.btnPrimary}>
            <div className={styles.actionIconWrapper}>
              <Icon icon="ri:send-plane-line" className={styles.iconAction} />
            </div>
            Resend Email
          </button>
          <button className={styles.btnSecondary}>
            <div className={styles.actionIconWrapper}>
              <Icon icon="ri:download-line" className={styles.iconAction} />
            </div>
            Download
          </button>
          <button
            onClick={onClose}
            className={styles.btnCloseAction}
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
}
